language: php
php:
    - '7.1'
    - '7.2'
install: composer install

env:
    - CODECOV_TOKEN="47d13c55-5188-40f2-9365-2a9d8a28d629"

before_script: pecl install xdebug-2.6.0beta1

script:
    - make cover

after_success:
    # Submit coverage report to https://codecov.io
    - bash <(curl -s https://codecov.io/bash)